Repository Safewaan/HonkedIn, pull requests merged in 2023-03, with the labels that each got.

#50 Gabbytang/find other profiles
  server.js
  src/components/App.js
  src/components/common/NavigationBar.js
  src/components/constants/Routes.js
  src/components/userNetwork/Network.js
  src/components/userNetwork/NetworkProfile.js
  src/components/users/ProfileDashboard.js
  src/routes/user/getUsers.js
  src/routes/userProfile/getUserProfile.js
Labels: front-end, back-end

#51 C45choi/view resources
  server.js
  src/components/App.js
  src/components/common/NavigationBar.js
  src/components/constants/Routes.js
  src/components/resources/CreateResource.js
  src/components/resources/Resources.js
  src/routes/resources/getResources.js
Labels: front-end, back-end

#52 Users can view their comments on a separate page
  server.js
  src/components/App.js
  src/components/common/NavigationBar.js
  src/components/constants/Routes.js
  src/components/forums/MyComments.js
  src/routes/forumComments/getForumCommentsByUserID.js
Labels: front-end, back-end

#49 Users can edit their own comments on a forum
  server.js
  src/components/forums/Forum.js
  src/components/forums/Forums.js
  src/components/forums/MyForums.js
  src/routes/forumComments/editForumComment.js
  src/routes/forumComments/getForumCommentsByForumID.js
Labels: front-end, back-end

#57 Styling for the Navigation Bar
  package-lock.json
  package.json
  src/components/App.js
  src/components/Dashboard.js
  src/components/common/NavigationBar.js
  src/components/events/CreateEvent.js
  src/components/events/Events.js
  src/components/events/MyEvents.js
  src/components/forums/CreateForum.js
  src/components/forums/Forum.js
  src/components/forums/Forums.js
  src/components/forums/MyForums.js
  src/components/resources/CreateResource.js
  src/components/resources/Resources.js
  src/components/userNetwork/NetworkProfile.js
  src/components/users/ProfileDashboard.js
  src/components/users/UpdateStatus.js
  src/images/Goose.png
  src/styles/navbar-style.css
Labels: front-end

#59 Users can add tags to Resources, and add/edits tags to Forums
  src/components/forums/CreateForum.js
  src/components/forums/MyForums.js
  src/components/resources/CreateResource.js
  src/routes/forums/createForum.js
  src/routes/forums/editForum.js
  src/routes/forums/getForumsByUserID.js
  src/routes/resources/createResource.js
Labels: front-end, back-end

#60 Implemented search function in forums and resources
  src/components/App.js
  src/components/common/Search.js
  src/components/events/Events.js
  src/components/events/MyEvents.js
  src/components/forums/Forums.js
  src/components/forums/MyForums.js
  src/components/resources/Resources.js
  src/components/userNetwork/Network.js
  src/routes/forums/getForums.js
  src/routes/forums/getForumsByUserID.js
  src/routes/resources/getResources.js
  src/styles/search-style.css
Labels: front-end, back-end

#63 C45choi/about us page
  src/components/App.js
  src/components/common/NavigationBar.js
  src/components/constants/Routes.js
  src/components/miscellaneous/AboutUs.js
Labels: front-end

#65 Users can filter the network, the resources, the forums and events by different fields
  package-lock.json
  package.json
  src/components/common/NavigationBar.js
  src/components/common/filters/ClearFilters.js
  src/components/common/filters/DateFilter.js
  src/components/common/filters/DropdownFilter.js
  src/components/common/filters/InputFilter.js
  src/components/common/filters/NumberFilter.js
  src/components/events/Events.js
  src/components/events/MyEvents.js
  src/components/forums/CreateForum.js
  src/components/forums/Forum.js
  src/components/forums/Forums.js
  src/components/forums/MyForums.js
  src/components/resources/CreateResource.js
  src/components/resources/Resources.js
  src/components/userNetwork/Network.js
  src/routes/forums/getForums.js
  src/routes/resources/getResources.js
  src/routes/user/getUsers.js
Labels: front-end, back-end

#66 Styling for Create Event, Create Forum Pages
  src/components/events/CreateEvent.js
  src/components/forums/CreateForum.js
  src/components/resources/CreateResource.js
Labels: front-end

#67 Users can view other's profiles info - Bug Fixed
  src/components/userNetwork/Network.js
Labels: front-end, hotfix

#68 Styling for all authentication related pages
  src/components/auth/ForgotPassword.js
  src/components/auth/Login.js
  src/components/auth/Signup.js
  src/components/auth/UpdateCredentials.js
  src/components/users/UpdateStatus.js
  src/components/users/UserSettings.js
  src/styles/style.css
Labels: front-end

#71 Add styling for create/edit profile page
  src/components/userNetwork/NetworkProfile.js
  src/components/users/ProfileDashboard.js
  src/routes/userProfile/editUserProfile.js
  src/routes/userProfile/getUserProfile.js
  src/styles/style.css
Labels: front-end, back-end

#73 Styling for About Us Page
  src/components/miscellaneous/AboutUs.js
Labels: front-end

#75 Fix styling for clear search button
  src/components/common/Search.js
Labels: front-end

#74 Add Styling for filter components
  src/components/common/filters/ClearFilters.js
  src/components/common/filters/DateFilter.js
  src/components/common/filters/DropdownFilter.js
  src/components/common/filters/InputFilter.js
  src/components/common/filters/NumberFilter.js
  src/components/events/Events.js
  src/components/events/MyEvents.js
  src/components/forums/Forums.js
  src/components/forums/MyForums.js
  src/components/resources/MyResources.js
  src/components/resources/Resources.js
  src/components/userNetwork/Network.js
  src/styles/style.css
Labels: front-end

#76 Styling for the network page, fix user routing when clicking on own profile
  src/components/userNetwork/Network.js
  src/routes/user/getUsers.js
Labels: front-end

#78 Style Events and My Events Page
  src/components/events/CreateEvent.js
  src/components/events/Events.js
  src/components/events/MyEvents.js
Labels: front-end

#80 Style Resources and My Resources Page
  src/components/resources/MyResources.js
  src/components/resources/Resources.js
Labels: front-end

#79 Style Forums and My Forums Page
  src/components/events/Events.js
  src/components/events/MyEvents.js
  src/components/forums/Forums.js
  src/components/forums/MyComments.js
  src/components/forums/MyForums.js
  src/components/resources/MyResources.js
Labels: front-end

#82 Styling for Forum and My Comments Page
  src/components/common/NavigationBar.js
  src/components/forums/Forum.js
  src/components/forums/MyComments.js
  src/styles/style.css
Labels: front-end

#81 Gabbytang/unit test 2
  tests/componentsTest/Network.js
  tests/jestTests/Network.test.js
Labels: tests

#83 Styling for Dashboard Page
  src/components/Dashboard.js
  src/components/events/Events.js
  src/components/events/MyEvents.js
  src/components/forums/Forums.js
  src/components/forums/MyForums.js
  src/components/resources/MyResources.js
  src/components/resources/Resources.js
  src/routes/dashboard/getMyEvents.js
  src/routes/dashboard/getPopularForums.js
  src/routes/dashboard/getRecentEvents.js
Labels: front-end

#84 Create Unit Test for Requests Page
  tests/componentsTest/Requests.js
  tests/jestTests/Requests.test.js
Labels: tests

#89 Time Changed for Daylight Savings Time
  src/components/Dashboard.js
  src/components/events/Events.js
  src/components/events/MyEvents.js
  src/components/forums/Forum.js
  src/components/forums/Forums.js
  src/components/forums/MyComments.js
  src/components/forums/MyForums.js
  src/components/resources/MyResources.js
  src/components/resources/Resources.js
Labels: hotfix

#88 Hotfix: Fix Profile Box Position
  src/components/userNetwork/NetworkProfile.js
  src/components/users/ProfileDashboard.js
Labels: front-end, hotfix

#90 Hotfix: Add date filters for Resources and My Resources
  src/components/resources/MyResources.js
  src/components/resources/Resources.js
Labels: front-end, hotfix

#91 Hotfix: Fix position for Titles on Requests Page
  src/components/users/Requests.js
Labels: front-end, hotfix

#93 Hotfix: Fix Card Positions
  src/components/auth/ForgotPassword.js
  src/components/auth/Login.js
  src/components/auth/Signup.js
  src/components/events/CreateEvent.js
  src/components/forums/CreateForum.js
  src/components/resources/CreateResource.js
Labels: front-end, hotfix

#94 Hotfix: Remove duplicate forget password link from Login
  src/components/auth/Login.js
Labels: front-end, hotfix

#92 Update Old Unit Tests
  tests/componentsTest/Events.js
  tests/componentsTest/Forum.js
  tests/componentsTest/Forums.js
  tests/componentsTest/MyComments.js
  tests/componentsTest/MyEvents.js
  tests/jestTests/Events.test.js
  tests/jestTests/Forum.test.js
  tests/jestTests/Forums.test.js
  tests/jestTests/MyComments.test.js
  tests/jestTests/MyEvents.test.js
Labels: tests

#95 Hotfix: Fix Update Status Header Text
  src/components/users/UpdateStatus.js
Labels: front-end, hotfix
