Repository Safewaan/HonkedIn, pull requests merged in 2023-02, with the labels that each got.

#10 Remove config file for security
  .gitignore
  config.js
Labels: config

#11 Create starter pages
  client/package.json
  client/src/components/Landing/index.js
  client/src/components/Navigation/PrivateRoute.js
  client/src/components/SignIn/index.js
  package.json
Labels: enhancement, front-end

#8 Remove Text Files in Main Directory Created for Lab 2
  Esha.txt
  Gabby.txt
  Safwaan.txt
  chloe.txt
Labels: cleanup

#14 Create API for user search given an email
  server.js
Labels: back-end

#15 cherry-pick to gabbytang/create-events: Create API for user search given an email
  server.js
Labels: back-end, cherry-pick

#16 Gabbytang/create events
  .gitignore
  package-lock.json
  package.json
  server.js
  src/components/App.js
  src/components/CreateEvent.js
  src/components/Events.js
Labels: front-end, back-end

#17 Users can join events, Event creators can set max participants
  package-lock.json
  package.json
  server.js
  src/components/CreateEvent.js
  src/components/Events.js
Labels: config, front-end, back-end

#18 Create routes directory for modular APIs
  routes/events/createEvent.js
  routes/events/getEvents.js
  routes/events/joinEvent.js
  routes/user/createUser.js
  routes/user/userSearchByEmail.js
  server.js
  src/components/CreateEvent.js
  src/components/Events.js
Labels: back-end

#21 Hotfix: Add error handling for when a user edits an event to have the maximum partipants allowed for an event lower than the actual number of participants
  src/components/MyEvents.js
Labels: front-end, back-end, hotfix

#24 Users can archive/activate their account, archived users cannot create events
  routes/user/activateUser.js
  routes/user/archiveUser.js
  server.js
  src/components/App.js
  src/components/CreateEvent.js
  src/components/Dashboard.js
  src/components/NavigationBar.js
  src/components/UpdateCredentials.js
  src/components/UpdateStatus.js
  src/components/UserSettings.js
Labels: front-end, back-end

#22 implemented 'see event participants' function on the My Events page
  routes/events/getParticipants.js
  server.js
  src/components/MyEvents.js
Labels: front-end, back-end

#13 Add Jest and Cypress dependencies for testing
  .babelrc
  cypress.config.js
  cypress/e2e/smoke.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/babel.config.js
  src/components/Link.js
  src/jest.config.js
  src/tests/Link.test.js
  src/tests/__snapshots__/Link.test.js.snap
Labels: config

#25 C45choi/create forums
  routes/forums/createForum.js
  server.js
  src/components/App.js
  src/components/CreateForum.js
  src/components/Dashboard.js
  src/components/NavigationBar.js
  src/components/UpdateCredentials.js
Labels: front-end, back-end

#26 Eshah7/profile main page
  routes/profile/createUserProfile.js
  routes/profile/editUserProfile.js
  routes/profile/getUserProfile.js
  server.js
  src/components/App.js
  src/components/NavigationBar.js
  src/components/ProfileDashboard.js
Labels: front-end, back-end

#28 Users can now visit the forums page to see all existing forums
  routes/forums/editForum.js
  routes/forums/getForums.js
  routes/forums/getForumsByUser.js
  server.js
  src/components/App.js
  src/components/Events.js
  src/components/Forums.js
  src/components/MyForums.js
  src/components/NavigationBar.js
Labels: front-end

#29 Users can expand a forum page, add comments and delete their own comments on a forum.
  routes/forums/createForumComment.js
  routes/forums/deleteForumComment.js
  routes/forums/getForumCommentsByForumID.js
  routes/forums/getForumsByForumID.js
  routes/forums/getForumsByUserID.js
  server.js
  src/components/App.js
  src/components/Events.js
  src/components/Forum.js
  src/components/Forums.js
  src/components/MyForums.js
Labels: front-end, back-end

#23 C45choi/landing page
  src/components/Dashboard.js
  src/components/NavigationBar.js
Labels: front-end

#34 Adding Archive button
  routes/forums/archiveForum.js
  routes/forums/getForumsByForumID.js
  server.js
  src/components/Forums.js
  src/components/MyForums.js
Labels: do-not-merge, front-end, back-end

#37 Users can no longer comment on Archived forums
  routes/forums/getForums.js
  src/components/Forum.js
  src/components/Forums.js
Labels: hotfix

#39 Create e2e test for the Login Page and routing to other pages
  cypress/.eslintrc.json
  cypress/e2e/login.cy.js
  cypress/e2e/smoke.cy.js
Labels: tests

#41 Update README and create schema directory for deployment of database
  README.md
  schema/eventParticipants.sql
  schema/events.sql
  schema/forumComments.sql
  schema/forums.sql
  schema/userProfiles.sql
  schema/users.sql
Labels: documentation, config

#42 Hotfix: fix routing to pages only accessible by users logged in
  src/components/App.js
Labels: back-end, hotfix

#45 Hotfix: fix createUser api not being called
  routes/user/createUser.js
Labels: back-end, hotfix
